x-pg-image: &pg-image postgres:16-alpine
x-kv-image: &kv-image docker.dragonflydb.io/dragonflydb/dragonfly:latest

x-pg-healthcheck: &pg-healthcheck
  interval: 5s
  timeout: 5s
  retries: 5

x-kv-healthcheck: &kv-healthcheck
  interval: 5s
  timeout: 5s
  retries: 5

services:
  app_server:
    profiles: [dev]
    build:
      context: .
      target: dev_target
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      app_data:
        condition: service_healthy
      app_kv:
        condition: service_healthy
    networks:
      - app_network

  app_kv:
    profiles: [dev, db]
    image: *kv-image
    ports:
      - "6379:6379"
    environment:
      - DFLY_requirepass=${KV_PASSWORD:-}
    volumes:
      - kv_data:/data
    mem_swappiness: 0
    ulimits:
      memlock: -1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      <<: *kv-healthcheck
    networks:
      - app_network

  test_kv:
    profiles: [test]
    image: *kv-image
    environment:
      - DFLY_requirepass=${KVTEST_PASSWORD:-}
    tmpfs:
      - /data
    mem_swappiness: 0
    ulimits:
      memlock: -1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      <<: *kv-healthcheck
    networks:
      - test_network

  app_data:
    profiles: [dev, db]
    image: *pg-image
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER}"]
      <<: *pg-healthcheck
    networks:
      - app_network

  schema_data:
    profiles: [db]
    image: *pg-image
    environment:
      POSTGRES_USER: ${PGSCHEMA_PLAN_USER}
      POSTGRES_PASSWORD: ${PGSCHEMA_PLAN_PASSWORD}
      POSTGRES_DB: ${PGSCHEMA_PLAN_DB}
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./db/init-plan:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGSCHEMA_PLAN_USER}"]
      <<: *pg-healthcheck
    depends_on:
      app_data:
        condition: service_healthy
    networks:
      - app_network

  test_data:
    profiles: [test]
    image: *pg-image
    environment:
      POSTGRES_USER: ${PGTEST_USER}
      POSTGRES_PASSWORD: ${PGTEST_PASSWORD}
      POSTGRES_DB: ${PGTEST_DATABASE}
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./db/init-test:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGTEST_USER}"]
      <<: *pg-healthcheck
    networks:
      - test_network

volumes:
  postgres_data:
  kv_data:

networks:
  app_network:
    driver: bridge
  test_network:
    driver: bridge
