// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPassword = `-- name: CreatePassword :one

INSERT INTO passwords (user_id, hash)
VALUES ($1, $2)
RETURNING id, user_id, hash, created_at
`

type CreatePasswordParams struct {
	UserID uuid.UUID `json:"user_id"`
	Hash   string    `json:"hash"`
}

// Password queries
// Passwords are append-only: INSERT for new password, old rows retained as history.
// Current password = ORDER BY created_at DESC LIMIT 1.
func (q *Queries) CreatePassword(ctx context.Context, arg CreatePasswordParams) (Password, error) {
	row := q.db.QueryRow(ctx, createPassword, arg.UserID, arg.Hash)
	var i Password
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentPasswordByEmail = `-- name: GetCurrentPasswordByEmail :one
SELECT p.id, p.user_id, p.hash, p.created_at FROM passwords p
JOIN users u ON u.id = p.user_id
WHERE u.email = $1
ORDER BY p.created_at DESC
LIMIT 1
`

// Used for login: fetches the current hash for a given email in one query.
func (q *Queries) GetCurrentPasswordByEmail(ctx context.Context, email string) (Password, error) {
	row := q.db.QueryRow(ctx, getCurrentPasswordByEmail, email)
	var i Password
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentPasswordByUserID = `-- name: GetCurrentPasswordByUserID :one
SELECT id, user_id, hash, created_at FROM passwords
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentPasswordByUserID(ctx context.Context, userID uuid.UUID) (Password, error) {
	row := q.db.QueryRow(ctx, getCurrentPasswordByUserID, userID)
	var i Password
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const listPasswordsByUserID = `-- name: ListPasswordsByUserID :many
SELECT id, user_id, hash, created_at FROM passwords
WHERE user_id = $1
ORDER BY created_at DESC
`

// Returns full password history for a user, newest first.
func (q *Queries) ListPasswordsByUserID(ctx context.Context, userID uuid.UUID) ([]Password, error) {
	rows, err := q.db.Query(ctx, listPasswordsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Password{}
	for rows.Next() {
		var i Password
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
