// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, display_name, role, verified, created_at, updated_at FROM users
WHERE id = $1
`

// Admin user queries.
// Auth-related queries (CreateUser, GetUserByEmail, UpdateUserEmail) are owned
// by pkg/auth/pgstore/sql/queries.sql and managed by that package.
// These queries support admin user management only.
// sqlc annotations control the return type:
//
//	:one  → returns a single struct
//	:many → returns []struct
//	:exec → returns error only
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasAdminUser = `-- name: HasAdminUser :one
SELECT EXISTS(SELECT 1 FROM users WHERE role = 'admin')
`

func (q *Queries) HasAdminUser(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdminUser)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, role, verified, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email        = COALESCE(NULLIF($1::text, ''), email),
    display_name = COALESCE(NULLIF($2::text, ''), display_name),
    role         = COALESCE(NULLIF($3::text, ''), role)
WHERE id = $4
RETURNING id, email, display_name, role, verified, created_at, updated_at
`

type UpdateUserParams struct {
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	Role        string    `json:"role"`
	ID          uuid.UUID `json:"id"`
}

// COALESCE(NULLIF(value, ”), column) means: empty string = keep existing value.
// sqlc.arg() assigns named parameters independent of positional $N numbering.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
