nav:
  brand:
    label: Starter
    href: /
  sections:
    - items:
        - label: Home
          href: /
        - label: Packages
          visibility: user
          items:
            - label: Componentry
              items:
                - label: Componnets
                  href: /_components
            - label: Auth
              items:
                - label: Users
                  href: /users
            - label: Site
              items:
                - label: Robots
                  href: /robots.txt
                - label: Sitemap
                  href: /sitemap.xml
    - align: end
      items:
        - label: Features
          items:
            - label: Documents
              href: /docs
        - label: Contact us
          href: /contact
        - label: Account
          items:
            - label: Sign In
              href: /signin
              visibility: guest
            - label: Sign Up
              href: /signup
              visibility: guest
            - slot: user_name
              visibility: user
            - slot: signout
              label: Signout
              visibility: user
        - slot: theme_toggle
