nav:
  brand:
    label: Starter
    href: /
  sections:
    - items:
        - label: Home
          href: /
        - label: Explore
          visibility: user
          items:
            - label: Components
              href: /_components
            - label: Admin
              items:
                - label: Users
                  href: /users
    - align: end
      items:
        - label: Sign In
          href: /signin
          visibility: guest
        - label: Sign Up
          href: /signup
          visibility: guest
        - slot: user_name
          visibility: user
        - slot: signout
          label: Signout
          visibility: user
        - slot: theme_toggle
