service:
  send:
    send_to: y-core@outlook.com
    delivery:
      selected: log
      providers:
        log: {}
        noop: {}
        memory: {}
        resend:
          api_key: ${EMAIL_API_KEY}
          send_from: admin@nutxport.com
        mailchannels:
          api_key: ${EMAIL_API_KEY}
          send_from: admin@nutxport.com
  auth:
    selected: email_totp
    methods:
      email_totp:
        enabled: true
        issuer: Forge
        period_seconds: 300
